import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import MenuNavbar from "./components/MenuNavbar";
import MarginWrapperComponent from "./components/MarginWrapperComponent";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300"],
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${inter.variable}`}>
        <MarginWrapperComponent>
          <MenuNavbar />
        </MarginWrapperComponent>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
